### ISSUE TITLE
请求新增自定义提示语

### ISSUE THREAD

**Issue by selfwong** [sbmatch/DeviceOptimizeHelper#10]
建议新增可修改的个性化提示语
![Screenshot_2024-08-15-20-46-34-618_com microsoft emmx](https://github.com/user-attachments/assets/9f03c7cf-7bee-4209-b778-d519ac517bf4)

“此设备归xxx所有”

**Comment by sbmatch** [comment]
在下个版本中会加入这个需求，敬请期待

**Comment by sbmatch** [comment]
已添加此功能 https://github.com/[sbmatch/DeviceOptimizeHelper](https://github.com/sbmatch/DeviceOptimizeHelper/releases/tag/v2.3.3)/releases/tag/v2.3.3
