### ISSUE TITLE
建议新增“刷新当前状态”按钮

### ISSUE THREAD

**Issue by selfwong** [sbmatch/DeviceOptimizeHelper#11]
![Screenshot_2024-08-15-20-47-18-462_ma DeviceOptimizeHelper](https://github.com/user-attachments/assets/17e9ed26-aa7c-48b2-8056-8ce1b1a9d866)
在右上角菜单里新增“状态更新”或“刷新”来更新规则启用与禁用的实时情况。

**Comment by sbmatch** [comment]
默认就是获取从系统中获取规则状态的，在启用或者禁用的时候也会有500ms延迟用于判断，如果禁用或者启用失败都会有提示的。所以不考虑这个功能
