### ISSUE TITLE
DISALLOW_DEBUGGING_FEATURES不是禁止USB调试

### ISSUE THREAD

**Issue by chenyue404** [sbmatch/DeviceOptimizeHelper#2]
DISALLOW_DEBUGGING_FEATURES是“[Specifies if a user is disallowed from enabling or accessing debugging features. ](https://developer.android.com/reference/android/os/UserManager#DISALLOW_DEBUGGING_FEATURES)”，实际表现是禁止使用开发者模式。

另外，禁止USB调试可以用[DevicePolicyManager.setUsbDataSignalingEnabled](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#setUsbDataSignalingEnabled(boolean))，虽然文档说它是“[停用 USB 数据信号传输](https://source.android.com/docs/core/interaction/accessories/disable-signaling)”，但是就我这边的实际表现来看，它只是阻止了USB调试。

**Comment by sbmatch** [comment]
好的，我会去修改它的描述为禁止使用开发者模式，此外，对于你说的[DevicePolicyManager.setUsbDataSignalingEnabled](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#setUsbDataSignalingEnabled(boolean)) 我会在Dhizuku模式下加入这一条限制策略

**Comment by sbmatch** [comment]
已在最新提交中加入了`void setUsbDataSignalingEnabled (boolean enabled)`方法的禁止USB调试限制，以及修改DISALLOW_DEBUGGING_FEATURES限制的描述为禁止开发者选项[commit: 96f31a98](https://github.com/sbmatch/DeviceOptimizeHelper/commit/96f31a9800fabf1de082398ffd789528e32cdf89)

**Comment by sbmatch** [comment]
我无法使用这个方法，随后会在最新分支中移除相关代码 请知悉

```
java.lang.IllegalStateException: USB data signaling cannot be disabled.
31578-31609 System.err              ma.DeviceOptimizeHelper              W  	at android.os.Parcel.createExceptionOrNull(Parcel.java:3019)
31578-31609 System.err              ma.DeviceOptimizeHelper              W  	at android.os.Parcel.createException(Parcel.java:2995)
31578-31609 System.err              ma.DeviceOptimizeHelper              W  	at android.os.Parcel.readException(Parcel.java:2978)
31578-31609 System.err              ma.DeviceOptimizeHelper              W  	at android.os.Parcel.readException(Parcel.java:2920)
31578-31609 System.err              ma.DeviceOptimizeHelper              W  	at ma.DeviceOptimizeHelper.IUserService$Stub$Proxy.setUsbDataSignalingEnabled(IUserService.java:554)
```
