### ISSUE TITLE
程序崩溃无法启动

### ISSUE THREAD

**Issue by is18g** [sbmatch/DeviceOptimizeHelper#6]
系统oneui6.1, Android 14 
[crash_2024_07_17_10_51_38.log](https://github.com/user-attachments/files/16258710/crash_2024_07_17_10_51_38.log)
附上崩溃日志

**Comment by sbmatch** [comment]
已修复 [@a344ce0](https://github.com/sbmatch/DeviceOptimizeHelper/commit/a344ce09d6356ae3b3fa67f81ef7cbca55d6684b) 请用最新1.8版本
